module.exports = [
  {
    linkedTo: "a1",
    choiceType: "goblin",
    score: 2500,
    health_lost: 0,
    alignment: "chaotic",
    choice: "*recites your name in gobish*",
  },
  {
    linkedTo: "a1",
    choiceType: "alien",
    score: 2500,
    health_lost: 0,
    alignment: "neutral",
    choice: '*Gurgles* "I\'m an alien!"',
  },
  {
    linkedTo: "a1",
    choiceType: "human",
    score: 2500,
    health_lost: 0,
    alignment: "lawful",
    choice: '"Hello There! Just an average human."',
  },
  {
    linkedTo: "a1",
    choiceType: "space_wizard",
    score: 1250,
    health_lost: 0,
    alignment: "lawful",
    choice: '*bows* "An elegant wizard at your service."',
  },
  {
    linkedTo: "a1",
    choiceType: "astral_thief",
    score: 1250,
    health_lost: 0,
    alignment: "neutral",
    choice: '*scoffs* "Ha, Thief Extraordinaire..."',
  },
  {
    linkedTo: "a1",
    choiceType: "cosmic_warrior",
    score: 1250,
    health_lost: 0,
    alignment: "chaotic",
    choice: '"GWARH! STRONG WARRIOR AM I!"',
  },
  {
    linkedTo: "a1",
    choiceType: "default",
    score: 1000,
    health_lost: 0,
    alignment: "neutral",
    choice: '"Hey there, just a pilot."',
  },
  {
    linkedTo: "a1",
    choiceType: "default",
    score: 1000,
    health_lost: 0,
    alignment: "neutral",
    choice: '"That\'s none of your business who I am to you."',
  },

  {
    linkedTo: "b1",
    choiceType: "goblin",
    score: 2500,
    health_lost: 0,
    alignment: "chaotic",
    choice: "Growl at the Manuels",
  },
  {
    linkedTo: "b1",
    choiceType: "alien",
    score: 2500,
    health_lost: 0,
    alignment: "lawful",
    choice: "Run an analysis in your head.",
  },
  {
    linkedTo: "b1",
    choiceType: "human",
    score: 2500,
    health_lost: 0,
    alignment: "neutral",
    choice: "Take a moment to think.",
  },
  {
    linkedTo: "b1",
    choiceType: "space_wizard",
    score: 1250,
    health_lost: 0,
    alignment: "lawful",
    choice: "Cast a spell to analyze the ship.",
  },
  {
    linkedTo: "b1",
    choiceType: "astral_thief",
    score: 1250,
    health_lost: 0,
    alignment: "neutral",
    choice: "Consult the stars",
  },
  {
    linkedTo: "b1",
    choiceType: "cosmic_warrior",
    score: 1250,
    health_lost: 0,
    alignment: "chaotic",
    choice: '"WHAT MANUEL?"',
  },
  {
    linkedTo: "b1",
    choiceType: "default",
    score: 1000,
    health_lost: 0,
    alignment: "lawful",
    choice: "Run an analysis on the ship.",
  },
  {
    linkedTo: "b1",
    choiceType: "default",
    score: 1000,
    health_lost: 0,
    alignment: "chaotic",
    choice: '"Wait did you mean manuals not Manuels?"',
  },

  {
    linkedTo: "b2",
    choiceType: "goblin",
    score: 2500,
    health_lost: 0,
    alignment: "chaotic",
    choice: "Play your Gwar Gwar drums",
  },
  {
    linkedTo: "b2",
    choiceType: "alien",
    score: 2500,
    health_lost: 0,
    alignment: "neutral",
    choice: "Ponder",
  },
  {
    linkedTo: "b2",
    choiceType: "human",
    score: 2500,
    health_lost: 0,
    alignment: "lawful",
    choice: "Find the engine manual",
  },
  {
    linkedTo: "b2",
    choiceType: "space_wizard",
    score: 1250,
    health_lost: 0,
    alignment: "lawful",
    choice: "Find your emergency scroll",
  },
  {
    linkedTo: "b2",
    choiceType: "astral_thief",
    score: 1250,
    health_lost: 0,
    alignment: "chaotic",
    choice: "Play your guitar",
  },
  {
    linkedTo: "b2",
    choiceType: "cosmic_warrior",
    score: 1250,
    health_lost: 0,
    alignment: "neutral",
    choice: '"THINK?"',
  },
  {
    linkedTo: "b2",
    choiceType: "default",
    score: 1000,
    health_lost: 0,
    alignment: "neutral",
    choice: "Humor the thought and move on",
  },
  {
    linkedTo: "b2",
    choiceType: "default",
    score: 1000,
    health_lost: 0,
    alignment: "lawful",
    choice: "Search for a toolbox",
  },

  {
    linkedTo: "b3",
    choiceType: "goblin",
    score: 2500,
    health_lost: 0,
    alignment: "chaotic",
    choice: "Spit and stab the engine to cool it.",
  },
  {
    linkedTo: "b3",
    choiceType: "alien",
    score: 2500,
    health_lost: 0,
    alignment: "lawful",
    choice: "Use your mind control to repair the engine",
  },
  {
    linkedTo: "b3",
    choiceType: "human",
    score: 2500,
    health_lost: 0,
    alignment: "neutral",
    choice: "Give into the panic",
  },
  {
    linkedTo: "b3",
    choiceType: "space_wizard",
    score: 1250,
    health_lost: 0,
    alignment: "lawful",
    choice: "Cast a cooling spell and begin repairs",
  },
  {
    linkedTo: "b3",
    choiceType: "astral_thief",
    score: 1250,
    health_lost: 0,
    alignment: "neutral",
    choice: "Use your star dagger to repair the engine",
  },
  {
    linkedTo: "b3",
    choiceType: "cosmic_warrior",
    score: 1250,
    health_lost: 0,
    alignment: "chaotic",
    choice: "PUNCH EVERYTHING",
  },
  {
    linkedTo: "b3",
    choiceType: "default",
    score: 1000,
    health_lost: 0,
    alignment: "neutral",
    choice: "Do nothing",
  },
  {
    linkedTo: "b3",
    choiceType: "default",
    score: 1000,
    health_lost: 0,
    alignment: "lawful",
    choice: "Repair the parts from your observation",
  },

  {
    linkedTo: "b4",
    choiceType: "goblin",
    score: 2500,
    health_lost: 0,
    alignment: "chaotic",
    choice: "Show them how goblins dance",
  },
  {
    linkedTo: "b4",
    choiceType: "alien",
    score: 2500,
    health_lost: 0,
    alignment: "lawful",
    choice: "Glare at them",
  },
  {
    linkedTo: "b4",
    choiceType: "human",
    score: 2500,
    health_lost: 0,
    alignment: "neutral",
    choice: "Offer them your open hand",
  },
  {
    linkedTo: "b4",
    choiceType: "space_wizard",
    score: 1250,
    health_lost: 0,
    alignment: "lawful",
    choice: "Cast the cretins to the next dimension",
  },
  {
    linkedTo: "b4",
    choiceType: "astral_thief",
    score: 1250,
    health_lost: 0,
    alignment: "lawful",
    choice: "Threaten them with your dagger",
  },
  {
    linkedTo: "b4",
    choiceType: "cosmic_warrior",
    score: 1250,
    health_lost: 0,
    alignment: "chaotic",
    choice: '"PARTY TIME"',
  },
  {
    linkedTo: "b4",
    choiceType: "default",
    score: 1000,
    health_lost: 0,
    alignment: "neutral",
    choice: "Coexists with them",
  },
  {
    linkedTo: "b4",
    choiceType: "default",
    score: 1000,
    health_lost: 0,
    alignment: "lawful",
    choice: "Kick them out",
  },

  {
    linkedTo: "c1",
    choiceType: "goblin",
    score: 2500,
    health_lost: 0,
    alignment: "chaotic",
    choice: '*rashberry noises* "Yooba-Dooba-Dooba"',
  },
  {
    linkedTo: "c1",
    choiceType: "alien",
    score: 2500,
    health_lost: 0,
    alignment: "lawful",
    choice: "Agree to help this human",
  },
  {
    linkedTo: "c1",
    choiceType: "human",
    score: 2500,
    health_lost: 0,
    alignment: "neutral",
    choice: '"Ok..I guess."',
  },
  {
    linkedTo: "c1",
    choiceType: "space_wizard",
    score: 1250,
    health_lost: 0,
    alignment: "chaotic",
    choice: '"I don\'t deal with criminals."',
  },
  {
    linkedTo: "c1",
    choiceType: "astral_thief",
    score: 1250,
    health_lost: 0,
    alignment: "neutral",
    choice: '"Outlaws should stick together."',
  },
  {
    linkedTo: "c1",
    choiceType: "cosmic_warrior",
    score: 1250,
    health_lost: 0,
    alignment: "neutral",
    choice: '"YOU STRONG ME HELP."',
  },
  {
    linkedTo: "c1",
    choiceType: "default",
    score: 1000,
    health_lost: 0,
    alignment: "neutral",
    choice: "Reluctantly agree",
  },
  {
    linkedTo: "c1",
    choiceType: "default",
    score: 1000,
    health_lost: 0,
    alignment: "chaotic",
    choice: "Decline his demands",
  },

  {
    linkedTo: "c2",
    choiceType: "goblin",
    score: 2500,
    health_lost: 0,
    alignment: "chaotic",
    choice: "Press the shiniest button",
  },
  {
    linkedTo: "c2",
    choiceType: "alien",
    score: 2500,
    health_lost: 0,
    alignment: "lawful",
    choice: "Use telekinesis to press all of the buttons",
  },
  {
    linkedTo: "c2",
    choiceType: "human",
    score: 2500,
    health_lost: 0,
    alignment: "chaotic",
    choice: "Press your favorite colored button",
  },
  {
    linkedTo: "c2",
    choiceType: "space_wizard",
    score: 1250,
    health_lost: 0,
    alignment: "lawful",
    choice: "Cast a spell to choose a button for you.",
  },
  {
    linkedTo: "c2",
    choiceType: "astral_thief",
    score: 1250,
    health_lost: 0,
    alignment: "neutral",
    choice: "Close your eyes and toss your dagger at the panel",
  },
  {
    linkedTo: "c2",
    choiceType: "cosmic_warrior",
    score: 1250,
    health_lost: 0,
    alignment: "neutral",
    choice: "Hurl your axe at the panel",
  },
  {
    linkedTo: "c2",
    choiceType: "default",
    score: 1000,
    health_lost: 0,
    alignment: "neutral",
    choice: "Press the blue button",
  },
  {
    linkedTo: "c2",
    choiceType: "default",
    score: 1000,
    health_lost: 0,
    alignment: "lawful",
    choice: "Press the red button",
  },

  {
    linkedTo: "c3",
    choiceType: "goblin",
    score: 2500,
    health_lost: 0,
    alignment: "chaotic",
    choice: "Jump down to surprise him",
  },
  {
    linkedTo: "c3",
    choiceType: "alien",
    score: 2500,
    health_lost: 0,
    alignment: "lawful",
    choice: "Speak to him with mind control.",
  },
  {
    linkedTo: "c3",
    choiceType: "human",
    score: 2500,
    health_lost: 0,
    alignment: "neutral",
    choice: "Play it safe and call to him from the vent",
  },
  {
    linkedTo: "c3",
    choiceType: "space_wizard",
    score: 1250,
    health_lost: 0,
    alignment: "lawful",
    choice: "Cast a projection of yourself in front of him.",
  },
  {
    linkedTo: "c3",
    choiceType: "astral_thief",
    score: 1250,
    health_lost: 0,
    alignment: "neutral",
    choice: "Remain unseen and talk to him from the vent",
  },
  {
    linkedTo: "c3",
    choiceType: "cosmic_warrior",
    score: 1250,
    health_lost: 0,
    alignment: "chaotic",
    choice: "Greet your fellow warrior like a man",
  },
  {
    linkedTo: "c3",
    choiceType: "default",
    score: 1000,
    health_lost: 0,
    alignment: "neutral",
    choice: "Call to him from the vent",
  },
  {
    linkedTo: "c3",
    choiceType: "default",
    score: 1000,
    health_lost: 0,
    alignment: "chaotic",
    choice: "Introduce yourself",
  },

  {
    linkedTo: "c4",
    choiceType: "goblin",
    score: 2500,
    health_lost: 0,
    alignment: "chaotic",
    choice: '"Run fast, hooman."',
  },
  {
    linkedTo: "c4",
    choiceType: "alien",
    score: 2500,
    health_lost: 0,
    alignment: "neutral",
    choice: '"Let\'s be smart about this, call the guard human."',
  },
  {
    linkedTo: "c4",
    choiceType: "human",
    score: 2500,
    health_lost: 0,
    alignment: "lawful",
    choice: '"Let\'s go the way I came"',
  },
  {
    linkedTo: "c4",
    choiceType: "space_wizard",
    score: 1250,
    health_lost: 0,
    alignment: "neutral",
    choice: "Cast a spell to trick the guard.",
  },
  {
    linkedTo: "c4",
    choiceType: "astral_thief",
    score: 1250,
    health_lost: 0,
    alignment: "lawful",
    choice: "Stay in the shadows, move through the vents.",
  },
  {
    linkedTo: "c4",
    choiceType: "cosmic_warrior",
    score: 1250,
    health_lost: 0,
    alignment: "chaotic",
    choice: "Break the glass cell and rush out.",
  },
  {
    linkedTo: "c4",
    choiceType: "default",
    score: 1000,
    health_lost: 0,
    alignment: "neutral",
    choice: "Tell the prisoner to call the guard",
  },
  {
    linkedTo: "c4",
    choiceType: "default",
    score: 1000,
    health_lost: 0,
    alignment: "lawful",
    choice: "Use the vents towards the yard",
  },

  {
    linkedTo: "c5",
    choiceType: "goblin",
    score: 2500,
    health_lost: 0,
    alignment: "chaotic",
    choice: '"Gwarspeh"',
  },
  {
    linkedTo: "c5",
    choiceType: "alien",
    score: 2500,
    health_lost: 0,
    alignment: "neutral",
    choice: "Read the prisoners mind for his name",
  },
  {
    linkedTo: "c5",
    choiceType: "human",
    score: 2500,
    health_lost: 0,
    alignment: "lawful",
    choice: '*laugh nervously* "Aren\'t all prisoners the same?"',
  },
  {
    linkedTo: "c5",
    choiceType: "space_wizard",
    score: 1250,
    health_lost: 0,
    alignment: "neutral",
    choice: '*wave your hand* "We are not the ones you\'re looking for"',
  },
  {
    linkedTo: "c5",
    choiceType: "astral_thief",
    score: 1250,
    health_lost: 0,
    alignment: "lawful",
    choice: "Persuade the guard",
  },
  {
    linkedTo: "c5",
    choiceType: "cosmic_warrior",
    score: 1250,
    health_lost: 0,
    alignment: "chaotic",
    choice: "Yell nonsense",
  },
  {
    linkedTo: "c5",
    choiceType: "default",
    score: 1000,
    health_lost: 0,
    alignment: "neutral",
    choice: "Joey",
  },
  {
    linkedTo: "c5",
    choiceType: "default",
    score: 1000,
    health_lost: 0,
    alignment: "lawful",
    choice: "Joseph",
  },

  {
    linkedTo: "c6",
    choiceType: "goblin",
    score: 650,
    health_lost: 0,
    alignment: "chaotic",
    choice: '"*rashberry noises* Yooba-Dooba-Dooba"',
  },
  {
    linkedTo: "c6",
    choiceType: "alien",
    score: 650,
    health_lost: 0,
    alignment: "lawful",
    choice: '"Passage to my home planet."',
  },
  {
    linkedTo: "c6",
    choiceType: "human",
    score: 650,
    health_lost: 0,
    alignment: "lawful",
    choice: '"A chance to go back to Earth Captain"',
  },
  {
    linkedTo: "c6",
    choiceType: "space_wizard",
    score: 1250,
    health_lost: 0,
    alignment: "neutral",
    choice: '"Spells, baubles, nicknacks of the sort"',
  },
  {
    linkedTo: "c6",
    choiceType: "astral_thief",
    score: 1250,
    health_lost: 0,
    alignment: "neutral",
    choice: '"A new dagger would be nice, then I\'ll call it even"',
  },
  {
    linkedTo: "c6",
    choiceType: "cosmic_warrior",
    score: 1250,
    health_lost: 0,
    alignment: "neutral",
    choice: '"ME? AXE STRONG SHINY"',
  },
  {
    linkedTo: "c6",
    choiceType: "default",
    score: 1000,
    health_lost: 0,
    alignment: "neutral",
    choice: '"A new ship?"',
  },
  {
    linkedTo: "c6",
    choiceType: "default",
    score: 1000,
    health_lost: 0,
    alignment: "chaotic",
    choice: '"I don\'t take handouts"',
  },

  {
    linkedTo: "d1",
    choiceType: "goblin",
    score: 2500,
    health_lost: 0,
    alignment: "chaotic",
    choice: '"Play Gwar Gwar beats"',
  },
  {
    linkedTo: "d1",
    choiceType: "alien",
    score: 2500,
    health_lost: 0,
    alignment: "chaotic",
    choice: '"Play Outerstellar music"',
  },
  {
    linkedTo: "d1",
    choiceType: "human",
    score: 2500,
    health_lost: 0,
    alignment: "lawful",
    choice: '"Play Rocking the Game"',
  },
  {
    linkedTo: "d1",
    choiceType: "space_wizard",
    score: 1250,
    health_lost: 0,
    alignment: "lawful",
    choice: '"Play Dropping Spells and Taking Names"',
  },
  {
    linkedTo: "d1",
    choiceType: "astral_thief",
    score: 1250,
    health_lost: 0,
    alignment: "neutral",
    choice: '"Play A Dance of Daggers"',
  },
  {
    linkedTo: "d1",
    choiceType: "cosmic_warrior",
    score: 1250,
    health_lost: 0,
    alignment: "chaotic",
    choice: '"PLAY AXE ME A QUESTION"',
  },
  {
    linkedTo: "d1",
    choiceType: "default",
    score: 1000,
    health_lost: 0,
    alignment: "neutral",
    choice: "Play Space is Cool",
  },
  {
    linkedTo: "d1",
    choiceType: "default",
    score: 1000,
    health_lost: 0,
    alignment: "lawful",
    choice: "Play Video Game Land",
  },
];
